(function(){
'use strict';
const C=window.TP_CONFIG||{}, API=(C.API_URL||'').trim();
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const path=()=>((location.pathname.replace(/^\/+|\/+$/g,'')||document.body.dataset.route||'home').replace(/\.html$/,''));
function mediaMap(d){return Object.fromEntries((d.media||[]).map(m=>[m.id,m]));}
function imgInfo(v,d){
  const map=mediaMap(d), m=map[v];
  if(m){
    const id=m.driveFileId||m.Drive_File_ID||m.fileId||'';
    return {src:id?`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1600`:'',alt:m.alt||m.Alt_Text||''};
  }
  if(/^https?:\/\//i.test(String(v||''))) return {src:String(v),alt:''};
  return {src:'',alt:''};
}
function im(v,d,alt='',cls=''){
  const x=imgInfo(v,d);
  if(!x.src) return `<div ${cls?`class="${cls} db-media-empty"`:'class="db-media-empty"'} aria-label="No image uploaded"></div>`;
  return `<img ${cls?`class="${cls}"`:''} loading="lazy" decoding="async" src="${esc(x.src)}" alt="${esc(alt||x.alt)}">`;
}
function fmtDate(s){if(!s)return'';const d=new Date(s+'T00:00:00');return isNaN(d)?s:new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(d)}
function fmtTime(t){if(!t)return'';const [h,m]=String(t).split(':').map(Number);if(Number.isNaN(h))return t;return new Intl.DateTimeFormat('en',{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,h,m||0));}
function routeFor(type,slug){const x=encodeURIComponent(slug||'');if(type==='series')return '/series/'+x;if(type==='news')return '/news/'+x;if(type==='event')return '/events/'+x;if(type==='artist')return '/artists/'+x;if(type==='merch')return '/merch/'+x;return'/';}
function pageCopy(d,k){return (d.pageCopy||[]).find(x=>x.page===k)||{eyebrow:k,heading:k,description:''};}
function adSlot(id,page){return `<aside class="ad-slot" data-slot="${esc(id)}" data-page="${esc(page||'')}" data-enabled="false" aria-hidden="true"></aside>`;}
function relatedHub(){return `<section class="section related-hub"><div class="wrap"><div class="eyebrow">Keep Exploring</div><h2 class="subhead">Continue the story.</h2><p class="related-intro">Everything connects — move between artists, series, current stories, events and collectibles.</p><div class="related-grid"><a href="/artists"><span>Artists</span><strong>Meet the artists</strong><small>Profiles and connected work →</small></a><a href="/series"><span>Series</span><strong>Explore their stories</strong><small>Ongoing and completed titles →</small></a><a href="/news"><span>News</span><strong>Latest updates</strong><small>Stories and announcements →</small></a><a href="/events"><span>Events</span><strong>See the calendar</strong><small>Events and episode releases →</small></a><a href="/merch"><span>Merch</span><strong>Browse collectibles</strong><small>Items connected to the fandom →</small></a></div></div></section>`}
function hero(c){return `<header class="hero center"><div class="wrap"><div class="eyebrow">${esc(c.eyebrow||'')}</div><h1>${esc(c.heading||c.title||'')}</h1><p>${esc(c.description||'')}</p></div></header>`}
function newsCard(n,d){const href=n.virtualHref||routeFor('news',n.slug);return `<article class="card news-card"><div class="media">${im(n.showcaseImage,d,n.showcaseTitle)}</div><div class="pad"><div class="meta"><span>${esc(n.category||'News')}</span><span>${esc(fmtDate(n.publishedDate))}</span></div><h3>${esc(n.showcaseTitle||n.title)}</h3><p>${esc(n.showcaseDescription||'')}</p><a class="btn" href="${esc(href)}">${n.virtual?'View Update':'Read More'}</a></div></article>`}
function seriesCard(s,d){return `<article class="series-card series-card-large"><div class="series-card-art">${im(s.image,d,s.title)}</div><div class="series-card-body"><div class="series-card-meta">${esc(s.year)} · ${esc(s.status)}${s.genres?` · ${esc(s.genres)}`:''}</div><h3>${esc(s.title)}</h3><p class="series-card-summary">${esc(s.summary||'')}</p><div class="series-card-actions"><a class="btn" href="${routeFor('series',s.slug)}">View Series</a><button class="btn alt series-quick-btn" type="button" data-series-quick="${esc(s.slug)}">Quick Info</button></div></div></article>`}
function seriesQuickModal(){return `<div class="series-quick-modal" id="series-quick-modal" aria-hidden="true"><div class="series-quick-backdrop" data-close-series-quick></div><section class="series-quick-dialog" role="dialog" aria-modal="true" aria-labelledby="series-quick-title"><button class="series-quick-close" type="button" aria-label="Close quick info" data-close-series-quick>×</button><div id="series-quick-content"></div></section></div>`}
function initSeriesQuickInfo(d){const modal=$('#series-quick-modal'),content=$('#series-quick-content');if(!modal||!content)return;const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('series-quick-open')};const open=slug=>{const s=(d.series||[]).find(x=>x.slug===slug);if(!s)return;content.innerHTML=`<div class="series-quick-hero">${im(s.image,d,s.title)}<div class="series-quick-shade"></div></div><div class="series-quick-body"><div class="eyebrow">Series · ${esc(s.status||'')}</div><h2 id="series-quick-title">${esc(s.title)}</h2><div class="series-quick-facts"><span>${esc(s.year||'')}</span>${s.genres?`<span>${esc(s.genres)}</span>`:''}${s.timezone?`<span>${esc(s.timezone)}</span>`:''}</div><p>${esc(s.summary||'')}</p><div class="series-card-actions"><a class="btn" href="${routeFor('series',s.slug)}">View Series</a><button class="btn alt" type="button" data-close-series-quick>Close</button></div></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('series-quick-open');$$('[data-close-series-quick]',modal).forEach(x=>x.onclick=close)};$$('[data-series-quick]').forEach(b=>b.onclick=()=>open(b.dataset.seriesQuick));$$('[data-close-series-quick]',modal).forEach(x=>x.onclick=close);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))close()},{once:false});}


function truthy(v){return v===true||String(v||'').toLowerCase()==='true'||String(v||'')==='1'||String(v||'').toLowerCase()==='yes';}
function published(x){const v=String(x.publishStatus??x.status??x.Publish_Status??x.Status??'Published').toLowerCase();return !['draft','archived','hidden','unpublished','disabled'].includes(v);}
function sourceKey(n){return `${String(n.sourceType||n.Source_Type||'').toLowerCase()}:${String(n.sourceId||n.Source_ID||'')}`;}
function deriveAutoNews(d){
  const manual=(d.news||[]).filter(published);
  const seen=new Set(manual.map(sourceKey).filter(x=>x!==':'));
  const out=[...manual];
  (d.series||[]).filter(published).forEach(s=>{
    const enabled=truthy(s.autoNews??s.Auto_News);
    const id=s.id||s.Series_ID||'';
    const key=`series:${id}`;
    if(!enabled||seen.has(key)) return;
    out.push({
      id:`auto-series-${id}`, slug:`series-${s.slug}`,
      title:`${s.title} added to the series library`,
      showcaseTitle:`New series: ${s.title}`,
      showcaseDescription:s.summary||'A new series has been added.',
      showcaseImage:s.image||'', category:'Series',
      publishedDate:s.releaseDate||s.Release_Date||s.createdAt||s.Created_At||'',
      relatedSeries:[s.slug], relatedArtists:s.relatedArtists||[],
      sourceType:'series', sourceId:id, autoGenerated:true,
      virtual:true, virtualHref:routeFor('series',s.slug)
    });
    seen.add(key);
  });
  (d.episodes||[]).filter(published).forEach(e=>{
    const enabled=truthy(e.autoNews??e.Auto_News);
    const sid=e.seriesId||e.Series_ID||'', no=e.episode??e.Episode_No??'';
    const id=e.id||e.Episode_ID||`${sid}-${no}`, key=`episode:${id}`;
    if(!enabled||seen.has(key)) return;
    const parent=(d.series||[]).find(s=>(s.id||s.Series_ID)===sid);
    if(!parent) return;
    out.push({
      id:`auto-episode-${id}`, slug:`episode-${parent.slug}-${no}`,
      title:`${parent.title} ${e.title||`Episode ${no}`} release update`,
      showcaseTitle:`${parent.title} — ${e.title||`Episode ${no}`}`,
      showcaseDescription:e.summary||`Release update for ${parent.title}.`,
      showcaseImage:e.image||e.Image||parent.image||'', category:'Episode',
      publishedDate:e.releaseDate||e.Release_Date||'',
      relatedSeries:[parent.slug], relatedArtists:parent.relatedArtists||[],
      sourceType:'episode', sourceId:id, autoGenerated:true,
      virtual:true, virtualHref:routeFor('series',parent.slug)
    });
    seen.add(key);
  });
  return out.sort((a,b)=>String(b.publishedDate||'').localeCompare(String(a.publishedDate||'')));
}
function prepareData(raw){
  const d=raw&&raw.data&&typeof raw.data==='object'?raw.data:raw||{};
  const keys=['links','adSlots','artists','series','episodes','news','events','merch','sitePages','notifications','media','pageCopy','homeSections'];
  keys.forEach(k=>{if(!Array.isArray(d[k]))d[k]=[]});
  if(!d.settings||typeof d.settings!=='object')d.settings={};
  d.artists=d.artists.filter(published);
  d.series=d.series.filter(published);
  d.episodes=d.episodes.filter(published);
  d.events=d.events.filter(published);
  d.merch=d.merch.filter(published);
  d.news=deriveAutoNews(d);
  return d;
}
function renderLoading(){
  const root=$('#tp-db-root'); if(!root)return;
  root.innerHTML=`<section class="db-loading"><div class="db-loading-inner"><span class="db-spinner" aria-hidden="true"></span><strong>Loading site content…</strong><small>Fetching the latest content from the database.</small></div></section>`;
}
function renderLoadError(){
  const root=$('#tp-db-root'); if(!root)return;
  root.innerHTML=`<section class="db-loading"><div class="db-loading-inner"><strong>Content temporarily unavailable.</strong><small>The public database could not be reached. Please refresh in a moment.</small><button class="btn" type="button" onclick="location.reload()">Retry</button></div></section>`;
}
function renderNotifications(d){
  const feed=$('#notification-feed'); if(!feed)return;
  const items=[...(d.notifications||[]).filter(published)].slice(0,4);
  if(!items.length){
    const news=(d.news||[]).slice(0,4);
    feed.innerHTML=news.length?news.map(n=>`<a class="notice-item" href="${esc(n.virtualHref||routeFor('news',n.slug))}"><b>${esc(n.showcaseTitle||n.title)}</b><small>${esc(n.category||'Update')}${n.publishedDate?` · ${esc(fmtDate(n.publishedDate))}`:''}</small></a>`).join(''):`<div class="notice-empty">No new updates yet.</div>`;
    return;
  }
  feed.innerHTML=items.map(n=>`<a class="notice-item" href="${esc(n.link||n.url||'/')}"><b>${esc(n.title||'Update')}</b><small>${esc(n.message||n.body||'')}</small></a>`).join('');
}

function renderHome(d){const hs=Object.fromEntries((d.homeSections||[]).map(x=>[x.type,x]));const h=hs.hero||{};const fs=hs['featured-series']||{};const target=fs.relatedId||fs.Related_ID||'';const s=(d.series||[]).find(x=>x.slug===target||x.id===target)||(d.series||[]).find(x=>String(x.status||'').toLowerCase()==='ongoing')||(d.series||[])[0];const artists=(d.artists||[]).slice(0,2),news=(d.news||[]).slice(0,3),merch=(d.merch||[])[0];return `<header class="hero center"><div class="wrap"><div class="eyebrow">${esc(h.eyebrow||d.settings?.siteName||'')}</div><h1>${esc(h.title||d.settings?.tagline||'')}</h1><p>${esc(h.description||d.settings?.description||'')}</p><div class="actions"><a class="btn" href="${esc(h.primaryLink||'/artists')}">${esc(h.primaryLabel||'Meet the Artists')}</a><a class="btn alt" href="${esc(h.secondaryLink||'/series')}">${esc(h.secondaryLabel||'Explore Series')}</a></div></div></header>${s?`<section class="home-featured-band"><div class="home-featured-inner"><div class="eyebrow">${esc(fs.eyebrow||'Featured · Ongoing')}</div><h2>${esc(s.title)}</h2><p>${esc(s.summary)}</p><div class="actions"><a class="btn" href="${routeFor('series',s.slug)}">${esc(fs.primaryLabel||'View Series')}</a><a class="btn alt" href="${esc(fs.secondaryLink||'/news')}">${esc(fs.secondaryLabel||'Read Story')}</a></div></div></section>`:''}${adSlot('home-mid','home')}<section class="section"><div class="wrap"><div class="eyebrow">${esc(hs.artists?.eyebrow||'Artists')}</div><h2 class="title">${esc(hs.artists?.title||'Meet the artists.')}</h2>${artists.map((a,i)=>`<div class="home-artist-showcase ${i%2?'reverse':''}"><div class="ha-copy"><div class="eyebrow">Artist ${String(i+1).padStart(2,'0')}</div><h2>${esc(a.name)}.</h2><p class="lede">${esc(a.fullName)} · ${esc(a.role)}</p><a class="btn" href="${routeFor('artist',a.slug)}">Meet ${esc(a.name)}</a></div><div class="ha-image">${im(a.image,d,a.name)}</div></div>${i===0?'<div style="height:18px"></div>':''}`).join('')}<p style="text-align:center;margin-top:24px"><a class="btn alt" href="/artists">Explore All Artists</a></p></div></section><section class="section home-news-section"><div class="wrap"><div class="eyebrow">${esc(hs.news?.eyebrow||'News')}</div><h2 class="title">${esc(hs.news?.title||'What’s happening.')}</h2><div class="grid3 db-news-grid">${news.map(n=>newsCard(n,d)).join('')}</div></div></section>${merch?`<section class="section"><div class="wrap"><div class="merch-showcase"><div class="copy"><div class="eyebrow">${esc(hs.merch?.eyebrow||'Merch')}</div><h2>${esc(hs.merch?.title||merch.title)}</h2><p class="lede">${esc(hs.merch?.description||merch.description)}</p><div><a class="btn" href="${esc(hs.merch?.primaryLink||'/merch')}">${esc(hs.merch?.primaryLabel||'Explore Merch')}</a></div></div><div class="merch-art">${im((merch.images||[])[0],d,merch.title)}</div></div></div></section>`:''}`}
function renderArtists(d){const c=pageCopy(d,'artists');return `${hero(c)}<section class="section"><div class="wrap"><div class="event-list">${(d.artists||[]).map((a,i)=>`<article class="event-card artist-list-card"><div class="event-gallery">${im(a.image,d,a.name)}</div><div class="event-copy"><div class="eyebrow">Artist ${String(i+1).padStart(2,'0')}</div><h2>${esc(a.name)}.</h2><p>${esc(a.fullName)} · ${esc(a.role)}</p><a class="btn" href="${routeFor('artist',a.slug)}">Explore Profile</a></div></article>`).join('')}</div></div></section>${relatedHub()}`}
function renderSeriesList(d){const c=pageCopy(d,'series');return `${hero(c)}<section class="section"><div class="wrap"><div class="series-grid series-grid-large">${(d.series||[]).map(s=>seriesCard(s,d)).join('')}</div></div></section>${adSlot('series-mid','series')}${seriesQuickModal()}${relatedHub()}`}
function renderNewsList(d){const c=pageCopy(d,'news'),items=d.news||[];return `${hero(c)}<section class="section tight"><div class="wrap"><div class="grid3 db-news-grid">${items.map(n=>newsCard(n,d)).join('')}</div></div></section>${adSlot('news-feed','news')}${relatedHub()}`}
function calendarMarkup(){return `<section class="section calendar-section"><div class="wrap"><div class="calendar-toolbar"><div><div class="eyebrow">Events & Releases Calendar</div><h2 class="subhead" id="calendar-title"></h2></div><div class="calendar-nav"><button type="button" id="cal-prev">←</button><button type="button" id="cal-today">Today</button><button type="button" id="cal-next">→</button></div></div><p class="calendar-help">Events and scheduled episode releases appear automatically on their dates.</p><div class="calendar-shell"><div class="calendar-weekdays"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="calendar-grid" id="event-calendar"></div></div></div></section><div class="event-modal" id="event-modal" aria-hidden="true"><div class="event-modal-backdrop" data-close-event></div><div class="event-modal-dialog"><div class="event-modal-head"><div><div class="eyebrow">On this date</div><h2 id="event-modal-title"></h2></div><button type="button" class="event-modal-close" data-close-event>×</button></div><div id="event-modal-content" class="event-modal-content"></div></div></div>`}
function renderEvents(d){const c=pageCopy(d,'events'),pics=[...(d.events||[]).slice(0,1).map(x=>x.image),...(d.artists||[]).slice(0,2).map(x=>x.image)].slice(0,3);return `<header class="events-hero"><div class="wrap events-hero-grid"><div class="events-hero-copy"><div class="eyebrow">${esc(c.eyebrow)}</div><h1 class="title">${esc(c.heading)}</h1><p class="lede">${esc(c.description)}</p></div><div class="events-photo-stack">${pics.map((p,i)=>`<span class="stack-photo ${['stack-photo-back','stack-photo-mid','stack-photo-front'][i]}">${im(p,d,'Event moment')}</span>`).join('')}</div></div></header>${adSlot('events-mid','events')}${calendarMarkup()}${relatedHub()}`}
function renderMerch(d){const c=pageCopy(d,'merch');return `${hero(c)}<section class="section" id="shop"><div class="wrap"><div class="product-grid">${(d.merch||[]).map(m=>{const prices=(m.variants||[]).map(v=>v.price).filter(Number.isFinite);const price=prices.length?Math.min(...prices):0;const currency=m.variants?.[0]?.currency||'';return `<article class="product"><div class="prod-art db-product-image">${im((m.images||[])[0],d,m.title)}</div><h3>${esc(m.title)}</h3><div class="price">${esc(currency)} ${esc(price)}</div><p>${esc(m.description)}</p><a class="btn" href="${routeFor('merch',m.slug)}">View Product</a></article>`}).join('')}</div></div></section>${adSlot('merch-feed','merch')}${relatedHub()}`}
function artistDetail(d,slug){const a=(d.artists||[]).find(x=>x.slug===slug);if(!a)return notFound();const relSeries=(d.series||[]).filter(s=>(s.relatedArtists||[]).includes(slug)),relNews=(d.news||[]).filter(n=>(n.relatedArtists||[]).includes(slug)).slice(0,3);return `<header class="profile-hero"><div class="profile-copy"><div class="eyebrow">Artist Profile</div><h1>${esc(a.name)}.</h1><p class="lede">${esc(a.fullName)}</p></div><div class="profile-image">${im(a.image,d,a.fullName)}</div></header><section class="profile-section"><div class="wrap"><div class="eyebrow">About</div><h2 class="title">${esc(a.role)}</h2><div class="story"><p>${esc(a.bio)}</p></div></div></section><section class="profile-section"><div class="wrap"><div class="eyebrow">Series</div><h2 class="title">On screen.</h2><div class="series-grid">${relSeries.map(s=>seriesCard(s,d)).join('')}</div></div></section>${relNews.length?`<section class="profile-section"><div class="wrap"><div class="eyebrow">News</div><h2 class="title">Latest connected stories.</h2><div class="grid3 db-news-grid">${relNews.map(n=>newsCard(n,d)).join('')}</div></div></section>`:''}${relatedHub()}`}
function seriesDetail(d,slug){const s=(d.series||[]).find(x=>x.slug===slug);if(!s)return notFound();const eps=(d.episodes||[]).filter(e=>e.seriesId===s.id).sort((a,b)=>a.episode-b.episode),arts=(d.artists||[]).filter(a=>(s.relatedArtists||[]).includes(a.slug)),news=(d.news||[]).filter(n=>(n.relatedSeries||[]).includes(slug)).slice(0,3),events=(d.events||[]).filter(e=>(e.relatedSeries||[]).includes(slug)).slice(0,3),merch=(d.merch||[]).filter(m=>(m.relatedSeries||[]).includes(slug)).slice(0,3);return `<header class="series-detail-hero">${im(s.image,d,s.title)}<div class="inside"><div class="eyebrow">Series · ${esc(s.status)}</div><h1>${esc(s.title)}</h1><p>${esc(s.year)} · ${esc(s.genres)}</p></div></header><section class="section tight"><div class="narrow"><div class="eyebrow">Synopsis</div><h2 class="title">${esc(s.title)}</h2><div class="series-synopsis"><p>${esc(s.summary)}</p></div></div></section>${eps.length?`<section class="section"><div class="wrap"><div class="eyebrow">Episodes</div><h2 class="title">Release tracker.</h2><div class="accordion"><div class="acc-body open">${eps.map(e=>`<div class="episode"><div class="ep-img">${im(s.image,d,s.title)}</div><div><span class="badge ${String(e.status).toLowerCase().includes('aired')?'blue':'pink'}">${esc(e.status)}</span><h4>${esc(e.title||('Episode '+e.episode))}</h4><p>${esc(e.summary||'')}</p></div><div class="release">${esc(fmtDate(e.releaseDate))}<br><small>${esc(fmtTime(e.releaseTime))} · ${esc(e.timezone)}</small></div></div>`).join('')}</div></div></div></section>`:''}${arts.length?`<section class="section"><div class="wrap"><div class="eyebrow">Featured Artists</div><h2 class="title">Go deeper.</h2><div class="featured-artists">${arts.map(a=>`<a class="artist-mini" href="${routeFor('artist',a.slug)}">${im(a.image,d,a.name)}<div class="pad"><h3>${esc(a.fullName)}</h3><p>${esc(a.role)}</p></div></a>`).join('')}</div></div></section>`:''}${news.length?`<section class="section"><div class="wrap"><div class="eyebrow">Related News</div><h2 class="title">Latest from ${esc(s.title)}.</h2><div class="grid3 db-news-grid">${news.map(n=>newsCard(n,d)).join('')}</div></div></section>`:''}${events.length?`<section class="section"><div class="wrap"><div class="eyebrow">Related Events</div><h2 class="title">Appearances & moments.</h2><div class="event-list">${events.map(e=>eventMini(e,d)).join('')}</div></div></section>`:''}${merch.length?`<section class="section"><div class="wrap"><div class="eyebrow">Merch</div><h2 class="title">Connected collection.</h2><div class="product-grid">${merch.map(m=>`<article class="product"><div class="prod-art db-product-image">${im((m.images||[])[0],d,m.title)}</div><h3>${esc(m.title)}</h3><a class="btn" href="${routeFor('merch',m.slug)}">View Product</a></article>`).join('')}</div></div></section>`:''}${relatedHub()}`}
function newsDetail(d,slug){const n=(d.news||[]).find(x=>x.slug===slug);if(!n)return notFound();return `<header class="hero"><div class="narrow"><div class="eyebrow">${esc(n.category||'News')} · ${esc(fmtDate(n.publishedDate))}</div><h1 style="font-size:clamp(44px,7vw,86px)">${esc(n.title)}</h1><p>${esc(n.showcaseDescription||'')}</p></div></header><section class="section tight"><div class="narrow"><div class="story db-story-blocks">${(n.blocks||[]).map(b=>b.type==='image'?`<figure class="db-article-image">${im(b.value,d,b.alt||n.title)}</figure>`:`<p>${esc(b.value)}</p>`).join('')}</div></div></section>${relatedHub()}`}
function eventMini(e,d){return `<article class="event-card db-event-mini"><div class="event-gallery">${im(e.image,d,e.title)}</div><div class="event-copy"><div class="eyebrow">${esc(fmtDate(e.date))}</div><h2>${esc(e.title)}</h2><p>${esc(e.venue)} · ${esc(fmtTime(e.time))}</p><a class="btn" href="${routeFor('event',e.slug)}">View Event Details</a></div></article>`}
function eventDetail(d,slug){const e=(d.events||[]).find(x=>x.slug===slug);if(!e)return notFound();const arts=(d.artists||[]).filter(a=>(e.relatedArtists||[]).includes(a.slug));return `<header class="events-hero"><div class="wrap events-hero-grid"><div class="events-hero-copy"><div class="eyebrow">Event</div><h1 class="title">${esc(e.title)}</h1><p class="lede">${esc(fmtDate(e.date))} · ${esc(fmtTime(e.time))} · ${esc(e.venue)}</p></div><div class="db-event-hero-image">${im(e.image,d,e.title)}</div></div></header><section class="section"><div class="wrap"><div class="series-info"><div class="fact"><b>Date</b>${esc(fmtDate(e.date))}</div><div class="fact"><b>Time</b>${esc(fmtTime(e.time))}</div><div class="fact"><b>Venue</b>${esc(e.venue)}</div><div class="fact"><b>Timezone</b>${esc(e.timezone)}</div></div></div></section><section class="section tight"><div class="narrow"><div class="eyebrow">About the Event</div><h2 class="title">Event details.</h2><div class="event-story db-story-blocks">${(e.blocks||[]).map(b=>b.type==='image'?`<figure class="db-event-content-image">${im(b.value,d,b.alt||e.title)}</figure>`:`<p>${esc(b.value)}</p>`).join('')}</div></div></section>${arts.length?`<section class="section"><div class="wrap"><div class="eyebrow">Featured Artists</div><h2 class="title">Connected artists.</h2><div class="featured-artists">${arts.map(a=>`<a class="artist-mini" href="${routeFor('artist',a.slug)}">${im(a.image,d,a.name)}<div class="pad"><h3>${esc(a.fullName)}</h3><p>${esc(a.role)}</p></div></a>`).join('')}</div></div></section>`:''}${relatedHub()}`}
function merchDetail(d,slug){const m=(d.merch||[]).find(x=>x.slug===slug)||(d.merch||[])[0];if(!m)return notFound();const imgs=m.images||[];return `<header class="hero"><div class="wrap"><div class="eyebrow">Merch · Product</div><h1>${esc(m.title)}</h1><p>${esc(m.description)}</p></div></header><section class="section tight"><div class="wrap grid2"><div class="card db-product-gallery"><div class="db-product-main">${im(imgs[0],d,m.title)}</div>${imgs.length>1?`<div class="db-gallery-dots">${imgs.map((_,i)=>`<button type="button" data-gallery-index="${i}" aria-label="Photo ${i+1}">${i?'○':'●'}</button>`).join('')}</div>`:''}</div><div class="formbox"><div class="eyebrow">Product Info</div><h2 class="subhead">${esc(m.title)}</h2><p class="lede">${esc(m.description)}</p><div class="db-variants">${(m.variants||[]).map(v=>`<label class="db-variant"><input type="radio" name="variant" ${v===m.variants[0]?'checked':''}><span>${esc(v.name)}</span><strong>${esc(v.currency)} ${esc(v.price)}</strong><small>${esc(v.status)}</small></label>`).join('')}</div></div></div></section>${relatedHub()}`}
function sitePage(d,slug){const p=(d.sitePages||[]).find(x=>x.slug===slug);if(!p)return notFound();return `<main><header class="page-hero"><div class="wrap"><div class="eyebrow">${esc(p.title)}</div><h1 class="title">${esc(p.heading)}</h1></div></header><section class="section"><div class="narrow"><div class="story"><p>${esc(p.body)}</p></div></div></section></main>`}
function notFound(){return `<header class="hero center"><div class="wrap"><div class="eyebrow">Not Found</div><h1>Content unavailable.</h1><p>This item may be unpublished or unavailable.</p><a class="btn" href="/">Back Home</a></div></header>`}
function render(d){
  const r=path(), root=$('#tp-db-root'); if(!root)return;
  let html='';
  if(r==='home'||r==='index') html=renderHome(d);
  else if(r==='artists') html=renderArtists(d);
  else if(r==='series') html=renderSeriesList(d);
  else if(r==='news') html=renderNewsList(d);
  else if(r==='events') html=renderEvents(d);
  else if(r==='merch') html=renderMerch(d);
  else if(r==='teshow'||r==='ping') html=artistDetail(d,r);
  else if(r.startsWith('series/')) html=seriesDetail(d,decodeURIComponent(r.slice(7)));
  else if(r.startsWith('news/')) html=newsDetail(d,decodeURIComponent(r.slice(5)));
  else if(r.startsWith('events/')) html=eventDetail(d,decodeURIComponent(r.slice(7)));
  else if(r.startsWith('artists/')) html=artistDetail(d,decodeURIComponent(r.slice(8)));
  else if(r.startsWith('merch/')) html=merchDetail(d,decodeURIComponent(r.slice(6)));
  else if(r==='product') html=merchDetail(d,new URLSearchParams(location.search).get('slug')||'');
  else if(['about','contact','privacy','terms'].includes(r)) html=sitePage(d,r);
  else html=notFound();
  root.innerHTML=html;
  bindImages(root); applySettings(d); renderNotifications(d); updateSEO(d,r); if(r==='events') initCalendar(d); if(r==='series') initSeriesQuickInfo(d); document.dispatchEvent(new CustomEvent('tp:rendered',{detail:d}));
}
function bindImages(scope=document){$$('img',scope).forEach(img=>{if(img.dataset.fbBound)return;img.dataset.fbBound='1';img.addEventListener('error',()=>{const f=img.dataset.fallback||'logo.png';if(img.src.endsWith(f))return;img.src=f;});});}
function applySettings(d){const s=d.settings||{};document.documentElement.dataset.adsEnabled=String(!!s.adsEnabled);$$('.footer-brand p').forEach(x=>x.textContent=s.description||x.textContent);$$('.footer-brand small,.footer-bottom span:last-child').forEach(x=>x.textContent=s.disclaimer||x.textContent);const msg=$('.floating-action');if(msg){msg.dataset.demo='';msg.onclick=()=>window.open(s.messageUrl||'#','_blank','noopener');}(d.links||[]).filter(x=>x.enabled).forEach(l=>{$$(`[data-link-id="${l.id}"]`).forEach(a=>{a.href=l.url||'#';if(l.newTab){a.target='_blank';a.rel='noopener'}})});mountAds(d);}
function mountAds(d){const global=!!d.settings?.adsEnabled,defaults=d.settings?.adsenseClient||'',slots=Object.fromEntries((d.adSlots||[]).map(x=>[x.id,x]));$$('.ad-slot[data-slot]').forEach(el=>{const cfg=slots[el.dataset.slot],on=!!(global&&cfg&&cfg.enabled);el.dataset.enabled=String(on);el.setAttribute('aria-hidden',String(!on));if(!on){el.replaceChildren();return;}const client=cfg.client||defaults,slot=cfg.slot||'';if(!client||!slot){el.dataset.enabled='false';el.setAttribute('aria-hidden','true');return;}const ins=document.createElement('ins');ins.className='adsbygoogle';ins.style.display='block';ins.dataset.adClient=client;ins.dataset.adSlot=slot;ins.dataset.adFormat='auto';ins.dataset.fullWidthResponsive='true';el.replaceChildren(ins);try{(window.adsbygoogle=window.adsbygoogle||[]).push({});}catch(_){}});if(global&&defaults&&!document.querySelector('script[data-tp-adsense]')){const sc=document.createElement('script');sc.async=true;sc.crossOrigin='anonymous';sc.dataset.tpAdsense='true';sc.src=`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(defaults)}`;document.head.appendChild(sc);}}
function setMeta(selector,attr,value){let el=$(selector);if(!el){el=document.createElement('meta');if(selector.includes('property='))el.setAttribute('property',selector.match(/property="([^"]+)/)?.[1]||'');else el.setAttribute('name',selector.match(/name="([^"]+)/)?.[1]||'');document.head.appendChild(el);}el.setAttribute(attr,value||'');}
function updateSEO(d,r){const site=d.settings?.siteName||'Teshow × Ping PH',base=(C.SITE_URL||location.origin).replace(/\/$/,'');let title=site,desc=d.settings?.description||'',type='website',item=null;const p=pageCopy(d,r);if(['artists','series','news','events','merch'].includes(r)){title=`${p.heading||p.eyebrow||r} · ${site}`;desc=p.description||desc;}item=(d.artists||[]).find(x=>routeFor('artist',x.slug).slice(1)===r)||(d.series||[]).find(x=>routeFor('series',x.slug).slice(1)===r)||(d.news||[]).find(x=>routeFor('news',x.slug).slice(1)===r)||(d.events||[]).find(x=>routeFor('event',x.slug).slice(1)===r)||(d.merch||[]).find(x=>routeFor('merch',x.slug).slice(1)===r);if(item){title=`${item.title||item.name} · ${site}`;desc=item.summary||item.bio||item.showcaseDescription||item.description||desc;type=(d.news||[]).includes(item)?'article':'website';}document.title=title;setMeta('meta[name="description"]','content',desc);setMeta('meta[property="og:title"]','content',title);setMeta('meta[property="og:description"]','content',desc);setMeta('meta[property="og:type"]','content',type);setMeta('meta[property="og:url"]','content',base+location.pathname);setMeta('meta[name="twitter:title"]','content',title);setMeta('meta[name="twitter:description"]','content',desc);let canon=$('link[rel="canonical"]');if(!canon){canon=document.createElement('link');canon.rel='canonical';document.head.appendChild(canon);}canon.href=base+location.pathname;let ld=$('#tp-structured-data');if(!ld){ld=document.createElement('script');ld.type='application/ld+json';ld.id='tp-structured-data';document.head.appendChild(ld);}const schema=item?{'@context':'https://schema.org','@type':type==='article'?'Article':'WebPage',name:item.title||item.name,url:base+location.pathname,description:desc}:{'@context':'https://schema.org','@type':'WebSite',name:site,url:base+'/',description:desc};ld.textContent=JSON.stringify(schema);}
function initCalendar(d){const grid=$('#event-calendar');if(!grid)return;const title=$('#calendar-title'),modal=$('#event-modal'),mt=$('#event-modal-title'),mc=$('#event-modal-content');const by={};(d.events||[]).forEach(e=>{(by[e.date]||(by[e.date]=[])).push({kind:'event',title:e.title,time:fmtTime(e.time),place:e.venue,url:routeFor('event',e.slug)})});(d.episodes||[]).filter(e=>e.releaseDate).forEach(e=>{const s=(d.series||[]).find(x=>x.id===e.seriesId);if(!s)return;(by[e.releaseDate]||(by[e.releaseDate]=[])).push({kind:'release',title:`${s.title} — ${e.title||('Episode '+e.episode)}`,time:fmtTime(e.releaseTime),place:'Episode Release',url:routeFor('series',s.slug)})});let v=new Date();v=new Date(Date.UTC(v.getUTCFullYear(),v.getUTCMonth(),1));const key=(y,m,day)=>`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;function draw(){const y=v.getUTCFullYear(),m=v.getUTCMonth(),first=new Date(Date.UTC(y,m,1)).getUTCDay(),days=new Date(Date.UTC(y,m+1,0)).getUTCDate();title.textContent=new Intl.DateTimeFormat('en',{month:'long',year:'numeric',timeZone:'UTC'}).format(v);grid.innerHTML='';for(let i=0;i<first;i++)grid.insertAdjacentHTML('beforeend','<span class="calendar-blank"></span>');for(let day=1;day<=days;day++){const k=key(y,m,day),arr=by[k]||[];const b=document.createElement('button');b.type='button';b.className='calendar-day'+(arr.length?' has-event':'');b.innerHTML=`<span class="day-number">${day}</span><span class="event-count ${arr.length?'':'empty'}">${arr.length?`${arr.length} ${arr.length===1?'item':'items'}`:'&nbsp;'}</span>`;b.onclick=()=>open(k,arr);grid.appendChild(b)}}function open(k,arr){mt.textContent=fmtDate(k);mc.innerHTML=arr.length?arr.map(x=>`<article class="event-summary"><div class="event-summary-top"><span class="status upcoming">${x.kind==='release'?'Series Release':'Event'}</span><span>${esc(x.time)}</span></div><h3>${esc(x.title)}</h3><p class="event-place">${esc(x.place)}</p><a class="btn" href="${esc(x.url)}">${x.kind==='release'?'View Series':'View Event Details'}</a></article>`).join(''):'<div class="no-events"><strong>No events scheduled for this date.</strong></div>';modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$$('[data-close-event]',modal).forEach(x=>x.onclick=close);$('#cal-prev').onclick=()=>{v=new Date(Date.UTC(v.getUTCFullYear(),v.getUTCMonth()-1,1));draw()};$('#cal-next').onclick=()=>{v=new Date(Date.UTC(v.getUTCFullYear(),v.getUTCMonth()+1,1));draw()};$('#cal-today').onclick=()=>{const n=new Date();v=new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),1));draw()};draw();}
async function load(){
  renderLoading();
  if(!API){renderLoadError();return;}
  try{
    const sep=API.includes('?')?'&':'?';
    const r=await fetch(API+sep+'action=publicContent',{credentials:'omit',cache:'no-store'});
    if(!r.ok)throw new Error('HTTP '+r.status);
    const data=prepareData(await r.json());
    render(data);
  }catch(e){
    console.error('Public content load failed',e);
    renderLoadError();
  }
}
load();
})();
