(function(){
const page=document.body.dataset.page||'home',root=document.querySelector('[data-shell-root]');if(!root)return;
const cfg=window.TP_CONFIG||{},api=String(cfg.API_URL||'');
const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const href=r=>{r=String(r||'/');if(/^https?:/i.test(r))return r;if(r==='/'||r==='')return 'index.html';return r.replace(/^\//,'').replace(/\.html$/,'')+'.html'};
const media=(url,label='Image coming soon',cls='')=>url?`<img class="${cls}" src="${esc(url)}" alt="">`:`<div class="cms-media-placeholder ${cls}"><span>${esc(label)}</span></div>`;
function header(d){const nav=(d.navigation||[]).map(n=>`<a href="${href(n.Route)}">${esc(n.Label)}</a>`).join('');return `<nav class="tp-nav"><a class="tp-brand" href="index.html"><img src="logo.png" alt="Teshow × Ping PH"></a><div class="tp-navlinks">${nav}</div><button class="tp-circle" id="themeBtn" aria-label="Toggle theme">☀</button><button class="tp-circle tp-bell" aria-label="Notifications">◇<span>4</span></button><button class="tp-menu" id="menuBtn" aria-label="Open menu">☰</button></nav><div class="tp-mobile-menu" id="mobileMenu">${nav}</div>`}
function hero(s){return `<section class="tp-hero"><div class="tp-hero-copy">${s.Eyebrow?`<div class="tp-eyebrow">${esc(s.Eyebrow)}</div>`:''}<h1>${esc(s.Title||'')}</h1>${s.Description?`<p>${esc(s.Description)}</p>`:''}<div class="tp-actions">${s.Primary_Label?`<a class="tp-btn primary" href="${href(s.Primary_Link)}">${esc(s.Primary_Label)}</a>`:''}${s.Secondary_Label?`<a class="tp-btn" href="${href(s.Secondary_Link)}">${esc(s.Secondary_Label)}</a>`:''}</div></div><div class="tp-hero-media">${media(s.image,'Image coming soon')}</div></section>`}
function featuredSeries(s,d){const list=d.series||[];const rel=list.find(x=>String(x.Slug)===String(s.Related_ID)||String(x.Series_ID)===String(s.Related_ID))||list[0];if(!rel)return'';return `<section class="tp-featured"><div class="tp-featured-intro"><div class="tp-eyebrow">${esc(s.Eyebrow||'Featured · Ongoing')}</div><h2>Featured<br>Series</h2><p>Follow their latest story and what’s coming next.</p><a class="tp-btn primary" href="series.html">View All Series</a></div><div class="tp-featured-media">${media(s.image||rel.image,'Series image coming soon')}</div><div class="tp-featured-copy"><div class="tp-eyebrow">${esc(rel.Status_Type||'Series')}</div><h3>${esc(rel.Title)}</h3><p>${esc(rel.Description||'')}</p><div class="tp-actions"><a class="tp-btn primary" href="${href('/'+(rel.Slug||'series'))}">View Series</a>${s.Secondary_Label?`<a class="tp-btn" href="${href(s.Secondary_Link)}">${esc(s.Secondary_Label)}</a>`:''}</div></div></section>`}
function artistsSection(s,d){const artists=(d.artists||[]).slice(0,2);if(!artists.length)return'';return `<section class="tp-section tp-artists"><div class="tp-section-kicker"><div class="tp-eyebrow">${esc(s.Eyebrow||'Artists')}</div><h2>${esc(s.Title||'Meet the artists.')}</h2></div>${artists.map((a,i)=>`<article class="tp-artist-row ${i%2?'reverse':''}"><div class="tp-artist-copy"><div class="tp-eyebrow">Artist ${String(i+1).padStart(2,'0')}</div><h3>${esc(a.Name)}.</h3><p>${esc([a.Full_Name,a.Role].filter(Boolean).join(' · '))}</p><a class="tp-btn primary" href="${href('/'+(a.Slug||'artists'))}">Meet ${esc(a.Name)}</a></div><div class="tp-artist-media">${media(a.image,'Artist photo coming soon')}</div></article>`).join('')}<div class="tp-center"><a class="tp-btn" href="artists.html">Explore All Artists</a></div></section>`}
function cards(type,items,s){if(!items.length)return'';const label=s?.Title||({news:'What’s happening.',events:'Events',merch:'Merch',series:'Series',artists:'Artists'}[type]||type);return `<section class="tp-section"><div class="tp-section-kicker"><div class="tp-eyebrow">${esc(s?.Eyebrow||type)}</div><h2>${esc(label)}</h2></div><div class="tp-grid">${items.map(x=>`<article class="tp-card"><div class="tp-card-media">${media(x.image||(x.images&&x.images[0]),'Image coming soon')}</div><div class="tp-card-copy"><h3>${esc(x.Name||x.Title||x.Showcase_Title||'')}</h3><p>${esc(x.Showcase_Description||x.Description||x.Bio||x.Venue||'')}</p></div></article>`).join('')}</div></section>`}
function eventsPage(d){return cards('events',d.events||[],{Eyebrow:'Events',Title:'Upcoming & recent events.'})}
function listPage(type,d){const item=d[type]||[];return cards(type,item,{Eyebrow:type,Title:{artists:'Meet the artists.',series:'Series',news:'What’s happening.',events:'Events',merch:'Merch'}[type]})}
function footer(){return `<footer class="tp-footer"><img src="logo.png" alt=""><p>Teshow × Ping PH</p></footer>`}
function shell(){return `<div class="shell-loading"><div class="skeleton sk-title"></div><div class="skeleton sk-line"></div><div class="skeleton hero-media-shell"></div></div>`}
async function start(){root.innerHTML=shell();if(!api||api.includes('PASTE_APPS_SCRIPT')){root.innerHTML='<main class="cms-empty-state"><p>CMS API not connected yet.</p></main>';return}try{const r=await fetch(api+(api.includes('?')?'&':'?')+'action=publicContent',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();render(d)}catch(e){console.error(e);root.innerHTML='<main class="cms-empty-state"><p>Unable to load CMS content.</p></main>'}}
function render(d){let body='';if(page==='home'){const hs=d.homeSections||[];for(const s of hs){const t=String(s.Type||'').toLowerCase();if(t==='hero')body+=hero(s);else if(t==='featured-series')body+=featuredSeries(s,d);else if(t==='artists')body+=artistsSection(s,d);else if(['news','events','merch','series'].includes(t))body+=cards(t,d[t]||[],s)}}else if(['artists','series','news','events','merch'].includes(page))body=listPage(page,d);else body='<section class="tp-section"><div class="tp-section-kicker"><h2>Content managed by CMS</h2></div></section>';root.innerHTML=header(d)+`<main>${body||'<section class="cms-empty-state"><p>No published content yet.</p></section>'}</main>`+footer();wire()}
function wire(){const menu=document.getElementById('menuBtn'),mm=document.getElementById('mobileMenu');if(menu&&mm)menu.onclick=()=>mm.classList.toggle('open');const tb=document.getElementById('themeBtn');if(tb)tb.onclick=()=>document.documentElement.classList.toggle('light')}
start();
})();
