(function(){
const page=document.body.dataset.page||'home',root=document.querySelector('[data-shell-root]');if(!root)return;
const cfg=window.TP_CONFIG||{}, api=String(cfg.API_URL||'');
const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const href=r=>r==='/'?'index.html':String(r||'').replace(/^\//,'')+'.html';
const placeholder=(label='Image coming soon')=>`<div class="cms-media-placeholder"><span>${esc(label)}</span></div>`;
function header(d){const nav=(d.navigation||[]).map(n=>`<a href="${href(n.Route)}">${esc(n.Label)}</a>`).join('');return `<header class="site-header"><div class="header-inner"><a class="brand" href="index.html"><img src="logo.png" alt="Teshow × Ping PH"></a><nav class="primary-nav">${nav}</nav></div></header>`}
function hero(s,d){const rel=(d.series||[]).find(x=>String(x.Slug)===String(s.Related_ID)||String(x.Series_ID)===String(s.Related_ID));const title=s.Title||rel?.Title||'',desc=s.Description||rel?.Description||'',img=s.image||rel?.image||'';return `<section class="cms-hero"><div class="cms-copy">${s.Eyebrow?`<p class="cms-eyebrow">${esc(s.Eyebrow)}</p>`:''}${title?`<h1>${esc(title)}</h1>`:''}${desc?`<p>${esc(desc)}</p>`:''}<div class="cms-actions">${s.Primary_Label?`<a class="cms-btn primary" href="${href(s.Primary_Link)}">${esc(s.Primary_Label)}</a>`:''}${s.Secondary_Label?`<a class="cms-btn" href="${href(s.Secondary_Link)}">${esc(s.Secondary_Label)}</a>`:''}</div></div>${img?`<img class="cms-hero-img" src="${esc(img)}" alt="">`:placeholder()}</section>`}
function cards(type,items){if(!items.length)return'';const label={artists:'Artists',series:'Series',news:'News',events:'Events',merch:'Merch'}[type]||type;return `<section class="cms-section"><div class="cms-section-head"><h2>${label}</h2></div><div class="cms-grid">${items.map(x=>{const title=x.Name||x.Title||x.Showcase_Title||'';const desc=x.Bio||x.Description||x.Showcase_Description||x.Venue||'';const img=x.image||(x.images&&x.images[0])||'';return `<article class="cms-card">${img?`<img src="${esc(img)}" alt="">`:placeholder()}<div class="cms-card-copy"><h3>${esc(title)}</h3>${desc?`<p>${esc(desc)}</p>`:''}</div></article>`}).join('')}</div></section>`}
function shell(){return `<div class="shell-loading"><div class="skeleton sk-title"></div><div class="skeleton sk-line"></div><div class="skeleton hero-media-shell"></div></div>`}
async function start(){root.innerHTML=shell();if(!api||api.includes('PASTE_APPS_SCRIPT')){root.innerHTML=`<main class="cms-empty-state"><p>CMS API not connected yet.</p></main>`;return}try{const r=await fetch(api+(api.includes('?')?'&':'?')+'action=publicContent',{cache:'no-store'});const d=await r.json();render(d)}catch(e){root.innerHTML=`<main class="cms-empty-state"><p>Unable to load CMS content.</p></main>`}}
function render(d){let body='';if(page==='home'){(d.homeSections||[]).forEach(s=>{const t=String(s.Type||'').toLowerCase();if(t==='hero'||t==='featured-series')body+=hero(s,d);else if(['artists','series','news','events','merch'].includes(t))body+=cards(t,d[t]||[])})}else if(page==='artists')body=cards('artists',d.artists||[]);else if(page==='series')body=cards('series',d.series||[]);else if(page==='news')body=cards('news',d.news||[]);else if(page==='events')body=cards('events',d.events||[]);else if(page==='merch')body=cards('merch',d.merch||[]);else body=`<section class="cms-section"><h1>Content managed by CMS</h1></section>`;root.innerHTML=header(d)+`<main>${body||'<section class="cms-empty-state"><p>No published content yet.</p></section>'}</main><footer class="shell-footer">Teshow × Ping PH</footer>`}
start();
})();
