"use client"
import { useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { formatLongDate, formatTime12, timezoneLabel } from '@/lib/utils'

function ymd(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}

export default function Calendar({events,episodes,labels={}}:{events:any[],episodes:any[],labels?:Record<string,string>}){
  const initial=new Date(); const [cursor,setCursor]=useState(new Date(initial.getFullYear(),initial.getMonth(),1)); const [selected,setSelected]=useState(ymd(initial)); const [active,setActive]=useState<any|null>(null); const ref=useRef<HTMLDialogElement>(null)
  const items=useMemo(()=>{ const map:Record<string,any[]>={}; const push=(date:string,item:any)=>{if(!date)return;(map[date]||=[]).push(item)}
    events.filter(e=>e.enabled!==false&&String(e.enabled).toLowerCase()!=='false').forEach(e=>push(String(e.start_date).slice(0,10),{...e,type:'event',title:e.title,href:`/events/${e.slug}`,quick:e.quick_info||e.short_info,full:e.full_info||e.description,time:e.start_time,timezone:e.timezone||'Asia/Bangkok'}))
    episodes.filter(e=>e.enabled!==false&&String(e.enabled).toLowerCase()!=='false').forEach(e=>push(String(e.release_date).slice(0,10),{...e,type:'episode',title:`${e.series_title?e.series_title+' • ':''}EP ${e.episode_number}`,href:`/series/${e.series_slug||''}`,quick:e.quick_info||e.summary||'Episode release',full:e.full_synopsis||e.summary,time:e.release_time,timezone:e.timezone||'Asia/Bangkok'})); return map
  },[events,episodes])
  const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),start=new Date(first);start.setDate(first.getDate()-first.getDay()); const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d}); const monthLabel=new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}).format(cursor)
  function openDay(key:string){setSelected(key);setActive(null);ref.current?.showModal()}
  const selectedItems=items[selected]||[]
  return <>
    <div className="calendar-shell"><div className="calendar-head"><button aria-label="Previous month" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}>←</button><div><p className="eyebrow">Schedule</p><h2>{monthLabel}</h2></div><button aria-label="Next month" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}>→</button></div><div className="weekday-row">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{days.map(d=>{const key=ymd(d),inMonth=d.getMonth()===cursor.getMonth(),dayItems=items[key]||[];return <button key={key} className={`calendar-day ${!inMonth?'muted':''} ${dayItems.length?'has-items':''}`} onClick={()=>openDay(key)}><span className="day-num">{d.getDate()}</span><span className="day-events">{dayItems.slice(0,2).map((x,i)=><span className={`cal-chip ${x.type}`} key={i}>{x.type==='episode'?'EP':'EVENT'} · {x.title}</span>)}{dayItems.length>2&&<span className="cal-more">+{dayItems.length-2} more</span>}</span></button>})}</div></div>
    <dialog ref={ref} className="calendar-dialog" onClick={e=>{if(e.currentTarget===e.target)ref.current?.close()}}><div className="calendar-modal"><button className="dialog-close" onClick={()=>ref.current?.close()} aria-label="Close">×</button><div className="panel-head"><div><p className="eyebrow">{labels.selected_date||'Selected date'}</p><h2>{formatLongDate(selected)}</h2></div></div>{!active?<div className="date-items">{selectedItems.length?selectedItems.map((x,i)=><button key={i} className="date-item" onClick={()=>setActive(x)}><span className={`date-type ${x.type}`}>{x.type}</span><div><h3>{x.title}</h3><p>{x.quick}</p>{x.time&&<small>{formatTime12(x.time)} • {timezoneLabel(x.timezone)}</small>}</div><b>→</b></button>):<div className="empty-card"><p>{labels.no_events||'No events or releases on this date.'}</p></div>}</div>:<div className="event-quick"><button className="back-link" onClick={()=>setActive(null)}>← Back to date</button><span className={`date-type ${active.type}`}>{active.type}</span><h2>{active.title}</h2>{active.time&&<p className="meta-line">{formatTime12(active.time)} • {timezoneLabel(active.timezone)}</p>}<p className="lede small">{active.quick}</p>{active.full&&<p className="muted-copy clamp-copy">{active.full}</p>}<Link className="button primary" href={active.href} onClick={()=>ref.current?.close()}>{active.type==='event'?'View Full Event':'View Series & Episode'}</Link></div>}</div></dialog>
  </>
}
