"use client"
import { useRef, useState } from 'react'
import MediaImage from './MediaImage'
import { formatLongDate, formatTime12, safeHref, timezoneLabel } from '@/lib/utils'

export default function EpisodeGrid({episodes,episodeCast,media,series}:{episodes:any[],episodeCast:any[],media:any[],series:any}){
  const [active,setActive]=useState<any|null>(null); const ref=useRef<HTMLDialogElement>(null)
  const mediaById=(id?:string)=>media.find(m=>m.media_id===id)
  function open(ep:any){setActive(ep);ref.current?.showModal()}
  const cast=active?episodeCast.filter(c=>c.episode_id===active.episode_id&&c.enabled!==false&&String(c.enabled).toLowerCase()!=='false').sort((a,b)=>Number(a.billing_order||99)-Number(b.billing_order||99)):[]
  return <><div className="episode-grid">{episodes.map(ep=>{const m=mediaById(ep.thumbnail_media_id||series.poster_media_id);return <button type="button" className="episode-card" key={ep.episode_id} onClick={()=>open(ep)}><div className="episode-visual"><MediaImage src={m?.url} alt={m?.alt_text||`${series.title} episode ${ep.episode_number}`} className="episode-image"/><span className="episode-number">EP {ep.episode_number}</span><span className={`episode-status ${ep.status||''}`}>{ep.status||'episode'}</span></div><div className="episode-copy"><p className="eyebrow">{formatLongDate(ep.release_date)}</p><h3>{ep.title||`Episode ${ep.episode_number}`}</h3><p>{ep.quick_info||ep.summary||'Open for episode details.'}</p><div className="episode-meta"><span>{formatTime12(ep.release_time)} {ep.release_time&&'•'} {ep.release_time?timezoneLabel(ep.timezone||'Asia/Bangkok'):''}</span>{ep.duration_minutes&&<span>{ep.duration_minutes} min</span>}</div><span className="text-link">View full episode info →</span></div></button>})}</div>
    <dialog ref={ref} className="episode-dialog" onClick={e=>{if(e.currentTarget===e.target)ref.current?.close()}}>{active&&<div className="episode-modal"><button className="dialog-close" onClick={()=>ref.current?.close()} aria-label="Close">×</button><div className="episode-modal-media"><MediaImage src={mediaById(active.thumbnail_media_id||series.poster_media_id)?.url} alt={active.title} className="episode-modal-image"/><span className="episode-number">EP {active.episode_number}</span></div><div className="episode-modal-copy"><p className="eyebrow">{series.title} • Episode {active.episode_number}</p><h2>{active.title||`Episode ${active.episode_number}`}</h2><div className="fact-pills"><span>{formatLongDate(active.release_date)}</span>{active.release_time&&<span>{formatTime12(active.release_time)} • {timezoneLabel(active.timezone||'Asia/Bangkok')}</span>}{active.rerun_time&&<span>Replay {formatTime12(active.rerun_time)} • {active.rerun_platform||series.platform||'oneD'}</span>}{active.duration_minutes&&<span>{active.duration_minutes} min</span>}</div><p className="lede small">{active.full_synopsis||active.summary||active.quick_info}</p>{cast.length>0&&<div className="episode-cast"><p className="eyebrow">Cast & characters</p><div className="cast-mini-grid">{cast.map(c=><div key={c.episode_cast_id}><strong>{c.actor_name||'Cast member'}</strong><span>{c.character_name||c.role_type||''}</span></div>)}</div></div>}<div className="card-actions">{active.watch_url&&<a className="button primary" href={safeHref(active.watch_url)} target="_blank" rel="noreferrer">Watch official</a>}{active.source_url&&<a className="button ghost" href={safeHref(active.source_url)} target="_blank" rel="noreferrer">Episode source ↗</a>}</div></div></div>}</dialog></>
}
